name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -e '.[test]'
    - name: set up 
      run: |
        python -m playwright install-deps
        shot-scraper install
        shot-scraper install -b firefox
        shot-scraper install -b webkit
    - name: Run tests
      run: |
        pytest
    - name: Check if cog needs to be run
      run: |
        cog --check docs/*.md
    - name: Run test examples
      run: |
        tests/run_examples.sh
    - name: Archive examples
      uses: actions/upload-artifact@v4
      with:
        name: examples-${{ matrix.python-version }}
        path: examples/*
